from PySide6 import QtWidgets


class SettingsDialog(QtWidgets.QDialog):
    def __init__(self, preferences, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Настройки QueryLens")
        self.setMinimumWidth(420)
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(24, 24, 24, 24)
        layout.setSpacing(18)
        title = QtWidgets.QLabel("Настройки")
        title.setObjectName("brand")
        layout.addWidget(title)
        form = QtWidgets.QFormLayout()
        form.setSpacing(16)
        self.theme = QtWidgets.QComboBox()
        self.theme.addItem("Тёмная", "dark")
        self.theme.addItem("Светлая", "light")
        self.theme.setCurrentIndex(self.theme.findData(preferences.theme))
        self.font_size = QtWidgets.QSpinBox()
        self.font_size.setRange(10, 20)
        self.font_size.setSuffix(" пт")
        self.font_size.setValue(preferences.font_size)
        self.history = QtWidgets.QCheckBox("Сохранять запуски анализа")
        self.history.setChecked(preferences.save_history)
        form.addRow("Тема", self.theme)
        form.addRow("Размер шрифта SQL", self.font_size)
        form.addRow(self.history)
        layout.addLayout(form)
        hint = QtWidgets.QLabel("История хранится локально на этом компьютере.\n"
                               "Отключение записи сохраняет прежние записи.")
        hint.setObjectName("muted")
        hint.setWordWrap(True)
        layout.addWidget(hint)
        buttons = QtWidgets.QDialogButtonBox()
        save = buttons.addButton("Применить", QtWidgets.QDialogButtonBox.ButtonRole.AcceptRole)
        save.setObjectName("primary")
        buttons.addButton("Отмена", QtWidgets.QDialogButtonBox.ButtonRole.RejectRole)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)
