from PySide6 import QtCore, QtWidgets
from app.ui.widgets.icons import make_icon


class DatabasePanel(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(16)
        header = QtWidgets.QHBoxLayout()
        title = QtWidgets.QLabel("Анализ базы данных")
        title.setObjectName("brand")
        header.addWidget(title)
        header.addStretch()
        self.tools_button = QtWidgets.QPushButton("Выбор инструментов")
        header.addWidget(self.tools_button)
        self.run_button = QtWidgets.QPushButton("Анализировать БД")
        self.run_button.setObjectName("primary")
        self.run_button.setEnabled(False)
        self.run_button.setToolTip("Запуск анализа появится после подключения анализаторов")
        header.addWidget(self.run_button)
        layout.addLayout(header)
        self.hint = QtWidgets.QLabel("Обзор структуры базы данных, конфигурации СУБД и ресурсов сервера.")
        self.hint.setObjectName("muted")
        self.hint.setWordWrap(True)
        layout.addWidget(self.hint)
        metrics = QtWidgets.QHBoxLayout()
        metrics.setSpacing(14)
        for title, caption in (("Таблицы", "Структура базы данных"),
                               ("Индексы", "Доступные индексы"), ("Размер БД", "Объём данных")):
            card, body = self.make_card(title)
            value = QtWidgets.QLabel("—")
            value.setObjectName("metricValue")
            body.addWidget(value)
            hint = QtWidgets.QLabel(caption)
            hint.setObjectName("muted")
            body.addWidget(hint)
            metrics.addWidget(card, 1)
        layout.addLayout(metrics)
        split = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal)
        split.setChildrenCollapsible(False)
        split.setHandleWidth(12)
        self.tables = QtWidgets.QTreeWidget()
        self.tables.setHeaderLabels(["Схема / таблица", "Поля", "Индексы"])
        self.tables.setRootIsDecorated(False)
        self.tables.setAccessibleName("Структура базы данных")
        self.tables.header().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tables.header().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.tables.header().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        structure, structure_layout = self.make_card("Структура базы данных")
        structure_layout.addWidget(self.tables, 1)
        structure_hint = QtWidgets.QLabel("Схемы, таблицы и индексы появятся после подключения СУБД.")
        structure_hint.setWordWrap(True)
        structure_hint.setObjectName("muted")
        structure_layout.addWidget(structure_hint)
        report, report_layout = self.make_card("Результаты анализа")
        report_layout.setSpacing(8)
        report_layout.addStretch()
        icon = QtWidgets.QLabel()
        icon.setPixmap(make_icon("chart", "#4b8cff").pixmap(44, 44))
        icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        report_layout.addWidget(icon)
        empty_title = QtWidgets.QLabel("Подключите базу данных")
        empty_title.setObjectName("section")
        empty_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        report_layout.addWidget(empty_title)
        empty_hint = QtWidgets.QLabel("Здесь появятся показатели,\nрезультаты проверок и рекомендации.")
        empty_hint.setObjectName("muted")
        empty_hint.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        report_layout.addWidget(empty_hint)
        self.connect_button = QtWidgets.QPushButton("Подключить СУБД")
        self.connect_button.setObjectName("primary")
        report_layout.addWidget(self.connect_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        report_layout.addStretch()
        tools_title = QtWidgets.QLabel("Выбранные инструменты")
        tools_title.setObjectName("section")
        report_layout.addWidget(tools_title)
        self.tool_states = {}
        for name in ("Config Analyzer", "Hardware Analyzer"):
            row = QtWidgets.QHBoxLayout()
            row.addWidget(QtWidgets.QLabel(name))
            row.addStretch()
            state = QtWidgets.QLabel()
            state.setObjectName("muted")
            row.addWidget(state)
            self.tool_states[name] = state
            report_layout.addLayout(row)
        preview = QtWidgets.QLabel("Предпросмотр · Анализаторы пока не подключены")
        preview.setObjectName("muted")
        preview.setWordWrap(True)
        report_layout.addWidget(preview)
        split.addWidget(structure)
        split.addWidget(report)
        split.setSizes([460, 660])
        layout.addWidget(split, 1)

    @staticmethod
    def make_card(title):
        card = QtWidgets.QFrame()
        card.setObjectName("card")
        body = QtWidgets.QVBoxLayout(card)
        body.setContentsMargins(20, 20, 20, 20)
        body.setSpacing(12)
        label = QtWidgets.QLabel(title)
        label.setObjectName("section")
        body.addWidget(label)
        return card, body

    def set_tools(self, names):
        for name, label in self.tool_states.items():
            label.setText("Выбран" if name in names else "Выключен")
